#!/bin/bash
echo "This script is about to run another script."
sh Bengali_HTS.sh out/input_1 out/hts_1.wav
sh Bengali_HTS.sh out/input_2 out/hts_2.wav
sh Bengali_HTS.sh out/input_3 out/hts_3.wav
sh Bengali_HTS.sh out/input_4 out/hts_4.wav
sh Bengali_HTS.sh out/input_5 out/hts_5.wav
sh Bengali_HTS.sh out/input_6 out/hts_6.wav
sh Bengali_HTS.sh out/input_7 out/hts_7.wav
sh Bengali_HTS.sh out/input_8 out/hts_8.wav
sh Bengali_HTS.sh out/input_9 out/hts_9.wav
sh Bengali_HTS.sh out/input_10 out/hts_10.wav
sh Bengali_HTS.sh out/input_11 out/hts_11.wav
sh Bengali_HTS.sh out/input_12 out/hts_12.wav
sh Bengali_HTS.sh out/input_13 out/hts_13.wav
sh Bengali_HTS.sh out/input_14 out/hts_14.wav
sh Bengali_HTS.sh out/input_15 out/hts_15.wav
sh Bengali_HTS.sh out/input_16 out/hts_16.wav
sh Bengali_HTS.sh out/input_17 out/hts_17.wav
sh Bengali_HTS.sh out/input_18 out/hts_18.wav
sh Bengali_HTS.sh out/input_19 out/hts_19.wav
sh Bengali_HTS.sh out/input_20 out/hts_20.wav
sh Bengali_HTS.sh out/input_21 out/hts_21.wav
sh Bengali_HTS.sh out/input_22 out/hts_22.wav
sh Bengali_HTS.sh out/input_23 out/hts_23.wav
sh Bengali_HTS.sh out/input_24 out/hts_24.wav
sh Bengali_HTS.sh out/input_25 out/hts_25.wav
sh Bengali_HTS.sh out/input_26 out/hts_26.wav
sh Bengali_HTS.sh out/input_27 out/hts_27.wav
sh Bengali_HTS.sh out/input_28 out/hts_28.wav
sh Bengali_HTS.sh out/input_29 out/hts_29.wav
sh Bengali_HTS.sh out/input_30 out/hts_30.wav
sh Bengali_HTS.sh out/input_31 out/hts_31.wav
sh Bengali_HTS.sh out/input_32 out/hts_32.wav
sh Bengali_HTS.sh out/input_33 out/hts_33.wav
sh Bengali_HTS.sh out/input_34 out/hts_34.wav
sh Bengali_HTS.sh out/input_35 out/hts_35.wav
sh Bengali_HTS.sh out/input_36 out/hts_36.wav
sh Bengali_HTS.sh out/input_37 out/hts_37.wav
sh Bengali_HTS.sh out/input_38 out/hts_38.wav
sh Bengali_HTS.sh out/input_39 out/hts_39.wav
sh Bengali_HTS.sh out/input_40 out/hts_40.wav
sh Bengali_HTS.sh out/input_41 out/hts_41.wav
sh Bengali_HTS.sh out/input_42 out/hts_42.wav
sh Bengali_HTS.sh out/input_43 out/hts_43.wav
sh Bengali_HTS.sh out/input_44 out/hts_44.wav
sh Bengali_HTS.sh out/input_45 out/hts_45.wav
sh Bengali_HTS.sh out/input_46 out/hts_46.wav
sh Bengali_HTS.sh out/input_47 out/hts_47.wav
sh Bengali_HTS.sh out/input_48 out/hts_48.wav
sh Bengali_HTS.sh out/input_49 out/hts_49.wav
sh Bengali_HTS.sh out/input_50 out/hts_50.wav
sh Bengali_HTS.sh out/input_51 out/hts_51.wav
sh Bengali_HTS.sh out/input_52 out/hts_52.wav
sh Bengali_HTS.sh out/input_53 out/hts_53.wav
sh Bengali_HTS.sh out/input_54 out/hts_54.wav
sh Bengali_HTS.sh out/input_55 out/hts_55.wav
sh Bengali_HTS.sh out/input_56 out/hts_56.wav
sh Bengali_HTS.sh out/input_57 out/hts_57.wav
sh Bengali_HTS.sh out/input_58 out/hts_58.wav
sh Bengali_HTS.sh out/input_59 out/hts_59.wav
sh Bengali_HTS.sh out/input_60 out/hts_60.wav
sh Bengali_HTS.sh out/input_61 out/hts_61.wav
sh Bengali_HTS.sh out/input_62 out/hts_62.wav
sh Bengali_HTS.sh out/input_63 out/hts_63.wav
sh Bengali_HTS.sh out/input_64 out/hts_64.wav
sh Bengali_HTS.sh out/input_65 out/hts_65.wav
sh Bengali_HTS.sh out/input_66 out/hts_66.wav
sh Bengali_HTS.sh out/input_67 out/hts_67.wav
sh Bengali_HTS.sh out/input_68 out/hts_68.wav
sh Bengali_HTS.sh out/input_69 out/hts_69.wav
sh Bengali_HTS.sh out/input_70 out/hts_70.wav
sh Bengali_HTS.sh out/input_71 out/hts_71.wav
sh Bengali_HTS.sh out/input_72 out/hts_72.wav
sh Bengali_HTS.sh out/input_73 out/hts_73.wav
sh Bengali_HTS.sh out/input_74 out/hts_74.wav
sh Bengali_HTS.sh out/input_75 out/hts_75.wav
sh Bengali_HTS.sh out/input_76 out/hts_76.wav
sh Bengali_HTS.sh out/input_77 out/hts_77.wav
sh Bengali_HTS.sh out/input_78 out/hts_78.wav
sh Bengali_HTS.sh out/input_79 out/hts_79.wav
sh Bengali_HTS.sh out/input_80 out/hts_80.wav
sh Bengali_HTS.sh out/input_81 out/hts_81.wav
sh Bengali_HTS.sh out/input_82 out/hts_82.wav
sh Bengali_HTS.sh out/input_83 out/hts_83.wav
sh Bengali_HTS.sh out/input_84 out/hts_84.wav
sh Bengali_HTS.sh out/input_85 out/hts_85.wav
sh Bengali_HTS.sh out/input_86 out/hts_86.wav
sh Bengali_HTS.sh out/input_87 out/hts_87.wav
sh Bengali_HTS.sh out/input_88 out/hts_88.wav
sh Bengali_HTS.sh out/input_89 out/hts_89.wav
sh Bengali_HTS.sh out/input_90 out/hts_90.wav
sh Bengali_HTS.sh out/input_91 out/hts_91.wav
sh Bengali_HTS.sh out/input_92 out/hts_92.wav
sh Bengali_HTS.sh out/input_93 out/hts_93.wav
sh Bengali_HTS.sh out/input_94 out/hts_94.wav
sh Bengali_HTS.sh out/input_95 out/hts_95.wav
sh Bengali_HTS.sh out/input_96 out/hts_96.wav
sh Bengali_HTS.sh out/input_97 out/hts_97.wav
sh Bengali_HTS.sh out/input_98 out/hts_98.wav
sh Bengali_HTS.sh out/input_99 out/hts_99.wav
sh Bengali_HTS.sh out/input_100 out/hts_100.wav
echo "The wav files are generated inside out folder."
